CREATE TABLE "Samples" ("sID" INTEGER NOT NULL,
                        "sName" TEXT NOT NULL,
                        "IntStdWv" FLOAT,
                        PRIMARY KEY ("sID")
                        );

CREATE TABLE "SampleIterations" ("iID" INTEGER NOT NULL,
                                 "sID" INTEGER NOT NULL,
                                 "sIteration" TEXT,
                                 "Si29_CPS" FLOAT,
                                 "Si29_CPS_Int2SE" FLOAT,
                                 "Na_ppm_m23" FLOAT,
                                 "Na2O wt%" FLOAT,
                                 "Ca_ppm_m43" FLOAT,
                                 "Ca_m43_wt%" FLOAT,
                                 "Ca_ppm_m44" FLOAT,
                                 "Ca_m44_wt%" FLOAT,
                                 "Ti_ppm_m49" FLOAT,
                                 "Ti wt%" FLOAT,
                                 "Ga_ppm_m69" FLOAT, 
                                 "Ga_ppm_m71" FLOAT, 
                                 "Rb_ppm_m85" FLOAT, 
                                 "Sr_ppm_m88" FLOAT, 
                                 "Y_ppm_m89" FLOAT, 
                                 "Zr_ppm_m90" FLOAT, 
                                 "Zr_ppm_m91" FLOAT, 
                                 "Nb_ppm_m93" FLOAT, 
                                 "Cs_ppm_m133" FLOAT, 
                                 "Ba_ppm_m137" FLOAT, 
                                 "La_ppm_m139" FLOAT, 
                                 "Ce_ppm_m140" FLOAT, 
                                 "Pr_ppm_m141" FLOAT, 
                                 "Nd_ppm_m146" FLOAT, 
                                 "Sm_ppm_m147" FLOAT, 
                                 "Eu_ppm_m153" FLOAT, 
                                 "Gd_ppm_m157" FLOAT, 
                                 "Tb_ppm_m159" FLOAT, 
                                 "Dy_ppm_m163" FLOAT, 
                                 "Ho_ppm_m165" FLOAT, 
                                 "Er_ppm_m166" FLOAT, 
                                 "Tm_ppm_m169" FLOAT, 
                                 "Yb_ppm_m172" FLOAT, 
                                 "Lu_ppm_m175" FLOAT, 
                                 "Hf_ppm_m178" FLOAT, 
                                 "Ta_ppm_m181" FLOAT, 
                                 "Pb_ppm_m208" FLOAT, 
                                 "Th_ppm_m232" FLOAT, 
                                 "U_ppm_m238" FLOAT,
                                 PRIMARY KEY ("iID", "sID"),
                                 FOREIGN KEY ("sID") REFERENCES "Samples"("sID")
                                 );
